### ISSUE TITLE
parse error when running bootstrap.inc

### ISSUE THREAD

**Issue by mrfaizal** [HTTPArchive/httparchive#46]
Tried following instructions here:
http://www.bbinto.me/performance/setup-your-own-http-archive-to-track-and-query-your-site-trends/

But when I got to bootstrap step I got the following error:
$ php bootstrap.inc
PHP Notice:  Undefined variable: gChromeDir in /var/www/httparchive/utils.inc on line 31
PHP Notice:  Undefined variable: gAndroidDir in /var/www/httparchive/utils.inc on line 32
PHP Parse error:  syntax error, unexpected '[' in /var/www/httparchive/crawls.inc on line 179

**Comment by stevesouders** [comment]
Fixed. Pull the latest version of settings.inc.

**Comment by mrfaizal** [comment]
Thanks Steve.  That fixed the PHP Notices about undefined variables but I still get the PHP Parse error.

**Comment by mrfaizal** [comment]
Seems like my version of PHP isn't parsing correctly.  If I expand function latestCrawlId into two lines then it parses fine:

$row = latestCrawl($archive, $beforeEpoch, $bFinished);
return $row['crawlid'];
